- src/components/Proposal/View/ProposalVoting/ProposalVotingSection.tsx
This closes https://github.com/decentraland/governance/issues/1782
> fix: Sign in to vote

- src/hooks/useGovernanceProfile.ts
> fix: stringify error message

- src/components/Common/Typography/Text.tsx
- src/components/Projects/ProjectSidebar.css
- src/components/Projects/ProjectSidebar.tsx
- src/components/Proposal/ProposalSidebar.tsx
- src/components/Proposal/Update/CollapsedProposalUpdate.tsx
- src/components/Proposal/Update/ProposalUpdate.css
- src/components/Proposal/Update/ProposalUpdate.tsx
- src/components/Sidebar/GovernanceSidebar.css
- src/components/Sidebar/GovernanceSidebar.tsx
- src/pages/proposal.tsx
> Project sidebar [in progress]

- src/components/GrantRequest/AddTeamMemberModal.tsx
- src/intl/en.json
- src/types/bids.ts
- src/types/grants.ts
> feat: add address field to team member modal

- src/components/BidRequest/BidRequestGeneralInfoSection.tsx
- src/components/GrantRequest/AddMilestoneModal.tsx
- src/components/GrantRequest/AddModal.css
- src/components/GrantRequest/GrantRequestGeneralInfoSection.tsx
- src/components/GrantRequest/MilestonesView.tsx
- src/components/Proposal/View/Categories/BidProposalView.tsx
- src/components/Proposal/View/Categories/GrantProposalView.tsx
- src/intl/en.json
- src/types/bids.ts
- src/types/grants.ts
- src/ui-overrides.css
Related to @decentraland/governance#1765
> feat: add milestones to grant submit

- src/types/proposals.ts
> chore: project links

- src/components/Projects/ActionablePersonnelView.tsx
- src/components/Projects/ProjectSidebarForm.css
- src/components/Projects/ProjectSidebarForm.tsx
- src/intl/en.json
Closes https://github.com/decentraland/governance/issues/1817
> feat: add optional label in project sheet form

- src/pages/project.tsx
> feat: add container to project page

- src/components/GrantRequest/BreakdownAccordion.tsx
- src/components/GrantRequest/MilestonesView.tsx
- src/components/GrantRequest/PersonnelView.tsx
- src/components/Projects/ActionablePersonnelView.tsx
- src/components/Projects/ExpandableBreakdownItem.tsx
> feat: hide subtitle in milestone proposal view

- src/components/Projects/ActionablePersonnelView.tsx
> feat: Address on personnel section

- src/intl/en.json
> feat: rename project sidebar cta

- src/components/Projects/MilestonesTab.tsx
- src/components/Sidebar/GovernanceSidebar.tsx
- src/intl/en.json
> fear: milestones empty state + sidebar loader fix

- src/components/Projects/ActionableLinksView.tsx
- src/components/Projects/ActionablePersonnelView.tsx
- src/components/Projects/ExpandableBreakdownItem.css
- src/components/Projects/MilestonesTab.tsx
- src/components/Projects/ProjectInfoCardsContainer.css
- src/components/Projects/ProjectInfoCardsContainer.tsx
- src/components/Projects/ProjectSectionsContainer.css
- src/components/Projects/ProjectSectionsContainer.tsx
- src/components/Projects/ProjectSheetStatusPill.tsx
- src/components/Projects/ProjectSidebarFormContainer.tsx
- src/components/Projects/Updates/PostUpdateBanner.css
- src/components/Projects/Updates/UpdatesTabView.tsx
- src/components/Proposal/Update/MiniProjectUpdateCard.css
- src/components/Proposal/Update/ProjectUpdateCard.css
> feat: improve spacing project sheet cards + fix update card border

- src/components/Projects/Updates/UpdatesTabView.tsx
- src/hooks/useIsProjectEditor.ts
- src/intl/en.json
> feat: Updates empty state

- src/components/Projects/Updates/PostUpdateBanner.tsx
- src/components/Projects/Updates/UpdatesTabView.tsx
- src/components/Proposal/Update/MiniProjectUpdateCard.css
- src/components/Proposal/Update/MiniProjectUpdateCard.tsx
- src/intl/en.json
> feat: Non mandatory updates text

- src/components/Projects/ActionableLinksView.tsx
- src/components/Projects/ActionablePersonnelView.tsx
- src/components/Projects/DeleteActionLabel.tsx
- src/components/Projects/MilestonesTab.tsx
- src/intl/en.json
> feat: delete confirmation modal for personnel, links and milestones

- src/components/Icon/CrossCircle.tsx
- src/components/Icon/InProgress.tsx
- src/components/Icon/PauseCircle.tsx
- src/components/Projects/ProjectGeneralInfo.tsx
- src/components/Projects/ProjectSheetStatusPill.tsx
- src/components/Projects/ProjectStatusCard.css
- src/components/Projects/ProjectStatusCard.tsx
- src/components/Projects/ProjectStatusCardWrapper.tsx
- src/intl/en.json
- src/utils/date/getDaysBetweenDates.ts
> feat: Project status card

- README.md
- src/clients/Governance.ts
- src/clients/Transparency.ts
- src/clients/VestingData.ts
- src/components/Profile/GrantBeneficiaryItem.tsx
- src/components/Profile/GrantBeneficiaryList.tsx
- src/components/Projects/Current/StatsAllProjects.tsx
- src/components/Projects/Current/StatsBiddingAndTendering.tsx
- src/components/Projects/ProjectCard/CliffProgress.tsx
- src/components/Projects/ProjectCard/ProgressBarTooltip.tsx
- src/components/Projects/ProjectCard/ProjectCard.tsx
- src/components/Projects/ProjectCard/VestingProgress.tsx
- src/components/Projects/ProjectGeneralInfo.tsx
- src/components/Proposal/View/AuthorDetails.tsx
- src/components/Proposal/View/ProjectCard.tsx
- src/components/Proposal/View/VestingContract.tsx
- src/hooks/useVestingContractData.ts
- src/intl/en.json
- src/types/grants.ts
- src/types/proposals.ts
- src/utils/committee.ts
- src/utils/projects.ts
- src/utils/proposal.ts
- src/utils/updates.ts
> feat: project vesting data

- src/components/Projects/ActionableLinksView.tsx
- src/components/Projects/ActionablePersonnelView.tsx
- src/components/Projects/MilestonesTab.tsx
- src/components/Projects/ProjectGeneralInfo.tsx
- src/components/Projects/ProjectView.tsx
- src/components/Projects/Updates/UpdatesTabView.tsx
- src/hooks/useIsProjectEditor.ts
> feat: Non editable projects

- src/components/Banner/Banner.css
- src/components/Banner/Banner.tsx
- src/components/Projects/Updates/PostUpdateBanner.tsx
- src/components/Proposal/View/ProjectSheetLink.css
Non mandatory update
Mandatory Update
> feat: project colors

- src/components/Projects/ProjectView.tsx
> chore: hide empty milestones

- src/components/Common/Empty.css
- src/components/Home/ActivityTicker.css
- src/components/Home/ActivityTickerList.css
- src/components/Home/ActivityTickerList.tsx
- src/components/Projects/MilestonesTab.tsx
- src/components/Projects/ProjectCard/VestingProgress.css
- src/components/Projects/ProjectCard/VestingProgressDatesText.tsx
- src/components/Projects/ProjectVerticalTab.css
- src/components/Projects/ProjectView.css
- src/components/Projects/ProjectView.tsx
- src/components/Projects/ProjectViewFundingSection.tsx
- src/components/Projects/Updates/UpdatesTabView.tsx
- src/intl/en.json
Pt 1 of [this bag of cats](https://github.com/decentraland/governance-ui/issues/121)
> feat: project view revised

- src/components/Icon/CrossCircle.tsx
- src/components/Icon/InProgress.tsx
- src/components/Icon/PauseCircle.tsx
- src/components/Projects/ProjectHealthCard.css
- src/components/Projects/ProjectHealthCard.tsx
- src/components/Projects/ProjectStatusCard.css
- src/components/Projects/ProjectStatusCard.tsx
- src/components/Projects/ProjectStatusCardWrapper.tsx
> feat: project status cards

- src/components/Events/ProposalRelatedEvent.tsx
- src/components/Events/utils.ts
- src/components/Home/ActivityTicker.tsx
- src/components/Home/ActivityTickerFilter.tsx
- src/components/Home/ActivityTickerList.tsx
- src/intl/en.json
- src/types/events.ts
Related to https://github.com/decentraland/governance/issues/1776
> feat: New project events

- src/clients/Governance.ts
- src/components/Modal/IdentityConnectModal/AccountsConnectModal.tsx
- src/components/Modal/IdentityConnectModal/DiscordConnect.tsx
- src/components/Modal/IdentityConnectModal/ForumConnect.tsx
- src/components/Modal/IdentityConnectModal/PushConnect.tsx
- src/components/Modal/IdentityConnectModal/UnlinkAcountCard.css
- src/components/Modal/IdentityConnectModal/UnlinkAcountCard.tsx
- src/intl/en.json
- src/types/users.ts
> feat: unlink accounts

- src/components/Modal/IdentityConnectModal/UnlinkAcountCard.tsx
- src/intl/en.json
> feat: add confirmation modal to unlink account action

- src/clients/Governance.ts
- src/components/Home/ActiveCommunityGrants.tsx
- src/components/Profile/ParticipatedProjectItem.tsx
- src/components/Profile/ParticipatedProjectsList.tsx
- src/components/Profile/ProjectsBox.tsx
- src/components/Projects/Current/CurrentProjectsList.tsx
- src/components/Projects/Current/StatsAllProjects.tsx
- src/components/Projects/Current/StatsBiddingAndTendering.tsx
- src/components/Projects/ProjectCard/ProjectCard.tsx
- src/components/Projects/ProjectCard/ProjectCardHeader.tsx
- src/components/Projects/ProjectCard/ProjectCardHeadline.tsx
- src/components/Proposal/View/AuthorDetails.tsx
- src/components/Proposal/View/ProjectCard.tsx
- src/components/Proposal/View/ProjectCardList.tsx
- src/hooks/useProjects.ts
- src/hooks/useProjectsByUser.ts
- src/pages/projects.tsx
- src/types/projects.ts
- src/types/proposals.ts
> chore: proposal projects deprecation

- src/constants/index.ts
- src/pages/submit/grant.tsx
- src/pages/submit/index.tsx
- src/pages/submit/pitch.tsx
> feat: hide grant and pitch proposal submission buttons

- src/components/Proposal/Submit/ProposalSubmitCatalystPage.tsx
- src/components/Proposal/Submit/ProposalSubmitHiringPage.tsx
- src/components/Proposal/Submit/ProposalSubmitPoiPage.tsx
- src/intl/en.json
- src/pages/submit/ban-name.tsx
- src/pages/submit/bid.tsx
- src/pages/submit/draft.tsx
- src/pages/submit/governance.tsx
- src/pages/submit/grant.tsx
- src/pages/submit/linked-wearables.tsx
- src/pages/submit/pitch.tsx
- src/pages/submit/poll.tsx
- src/pages/submit/tender.tsx
- src/pages/submit/update.tsx
- src/utils/imageValidation.test.ts
- src/utils/imageValidation.ts
> fix: images url check

- src/intl/en.json
> chore: add trusted domains list to images validation error message

- src/utils/analytics.ts
Start using getAnalytics from decentraland-dapps
> feat: use analytics from decentraland-dapps
